"""Configuration constants."""

NUM_DISTRICTS = 12
HISTORY_MONTHS = 36
EVAL_HORIZON_START = 36
EVAL_HORIZON_END = 41  # Inclusive
EVAL_MONTHS = EVAL_HORIZON_END - EVAL_HORIZON_START + 1
GLOBAL_RESERVE = 60
DEFAULT_SEED = 20260911
